server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mariadb://192.168.5.61:3306/userdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
